version: 1
formatters:
  simple:
    format: "[%(name)s] %(message)s"
  complex:
    format: "[%(asctime)s] [%(filename)s > %(funcName)s > %(lineno)d] : %(message)s"
    datefmt: "%Y-%m-%d %H:%M"
handlers:
  console:
    class: logging.StreamHandler
    formatter: complex
    stream: ext://sys.stdout
    level: DEBUG
  file:
    class: logging.FileHandler
    filename: log.log
    encoding: utf-8
    formatter: complex
    level: DEBUG
root:
  handlers: ["console", "file"]
disable_existing_loggers: false