trainer:
  name: DefaultTrainer
meta_architecture:
  name: U2NET
  architecture_dict:
    rsu-e7: [3, 32, 64]
    rsu-e6: [64, 32, 128]
    rsu-e5: [128, 64, 256]
    rsu-e4: [256, 128, 512]
    rsu-4f-1: [512, 256, 512]
    rsu-4f-2: [512, 256, 512]
    rsu-4f-3: [1024, 256, 512]
    rsu-d4: [1024, 128, 256]
    rsu-d5: [512, 64, 128]
    rsu-d6: [256, 32, 64]
    rsu-d7: [128, 16, 64]
loss:
  name: BinaryCrossEntropy